In [4]:
import numpy as np
from collections import OrderedDict

In [5]:
res = np.load('results/result-adv-gd-K=5-lam=1.0-id=1.npz')

In [7]:
dict(res)['mu']

array([[ 0.02695696,  0.3892387 ],
       [-0.9821752 ,  0.5880099 ],
       [ 2.0936265 ,  2.367144  ],
       [-1.7250005 , -0.6260999 ],
       [ 0.14382298,  0.31137154]], dtype=float32)

In [11]:
dict(res)['pi']

array([0.05940462, 0.00242822, 0.9332864 , 0.00159   , 0.00329076],
      dtype=float32)

In [12]:
dict(res)['cov']

array([[[ 0.33817983, -0.60115767],
        [-0.60115767,  1.2504479 ]],

       [[ 1.8434855 ,  0.2858621 ],
        [ 0.2858621 ,  0.04432755]],

       [[ 1.5729421 , -0.70187074],
        [-0.70187074,  2.59194   ]],

       [[ 2.116781  ,  0.5681834 ],
        [ 0.5681834 ,  1.6204158 ]],

       [[ 1.5867405 , -0.9584579 ],
        [-0.9584579 ,  1.2351351 ]]], dtype=float32)

In [8]:
dict(res).keys()

dict_keys(['pi', 'mu', 'train_d_losses', 'cov', 'test_p_losses', 'test_d_losses', 'train_p_losses'])

In [10]:
train_p_losses = res['train_p_losses']
train_d_losses = res['train_d_losses']
train_a_losses = [td - tp for td, tp in zip(train_d_losses, train_p_losses)]
train_a_losses[::100]

[0.053652286529541016,
 0.001096487045288086,
 0.0005145072937011719,
 0.0005948543548583984,
 0.0003724098205566406,
 0.0002613067626953125,
 0.0002028942108154297,
 0.00015974044799804688]

In [8]:
dict(d)

{'a': 1, 'b': 2}