In [1]:
import numpy as np

In [4]:
def MoG_generation(K=5, data_dim=2, data_range=5.0, data_n=1000):
    pi_logits = np.random.sample(K)
    pi = pi_logits / np.sum(pi_logits)

    mu_list = []
    for i in range(K):
        mu_i = np.random.sample(data_dim) * data_range
        mu_list.append(mu_i)
    mu = np.array(mu_list)
    
    # Now, covariance = I

    samples_list = []
    for i in range(data_n):
        normal_sample = np.random.randn(data_dim)
        cls = np.random.randint(K)
        sample = normal_sample + mu[cls]
        samples_list.append(sample)
    samples = np.array(samples_list)
    
    adv_l = [[]]
    for i in range(data_dim):
        _l = []
        for v in adv_l:
            _l.append(v + [-1.0])
            _l.append(v + [data_range + 1.0])
        adv_l = _l
    
    adv_sample = np.array(adv_l)
    
    return pi, mu, samples, adv_sample

In [5]:
pi, mu, samples, adv_sample = MoG_generation()

In [6]:
pi

array([0.14526003, 0.27931019, 0.09112876, 0.24044514, 0.24385588])

In [7]:
mu

array([[0.56162827, 4.06380063],
       [3.28073912, 4.35204736],
       [2.60321801, 1.87409632],
       [4.89483546, 0.49599283],
       [4.79015886, 2.42480232]])

In [8]:
samples[::50]

array([[ 1.35825423,  1.83219772],
       [ 2.64319305,  5.224342  ],
       [ 3.95274471,  2.33048396],
       [ 4.16059167,  4.83385209],
       [ 2.60659948,  3.98019731],
       [ 4.69456321,  4.273666  ],
       [ 4.61808618,  3.2075684 ],
       [ 2.6820898 ,  0.32647153],
       [ 5.88144678,  1.69764036],
       [ 3.44042735,  1.80054985],
       [ 5.98082642,  2.4237591 ],
       [ 4.98240089,  3.92803802],
       [ 2.37520765,  4.38722706],
       [ 3.08427474,  4.29565068],
       [ 3.91107336,  0.31629604],
       [-0.72826058,  4.80255559],
       [ 2.7906875 ,  6.52147993],
       [ 1.62396685,  3.24004962],
       [ 4.53024081, -0.8168355 ],
       [ 0.26723774,  2.81160355]])

In [9]:
adv_sample

array([[-1., -1.],
       [-1.,  6.],
       [ 6., -1.],
       [ 6.,  6.]])

In [ ]:
data_fname = 'data_multi_adv.npz'
np.savez(data_fname, pi=pi, mu=mu, samples=samples, adv_sample=adv_sample)