In [1]:
import numpy as np

In [10]:
def MoG_generation(K=5, data_dim=2, data_range=5.0, data_n=1000):
    pi_logits = np.random.sample(K)
    pi = pi_logits / np.sum(pi_logits)

    mu_list = []
    for i in range(K):
        mu_i = np.random.sample(data_dim) * data_range
        mu_list.append(mu_i)
    mu = np.array(mu_list)
    
    # Now, covariance = I

    samples_list = []
    for i in range(data_n):
        normal_sample = np.random.randn(data_dim)
        cls = np.random.randint(K)
        sample = normal_sample + mu[cls]
        samples_list.append(sample)
    samples = np.array(samples_list)
    
    adv_sample = np.ones(data_dim, dtype=np.float) * (-1)
    
    return pi, mu, samples, adv_sample

In [11]:
pi, mu, samples, adv_sample = MoG_generation()

In [12]:
pi

array([0.23705428, 0.06574439, 0.39978303, 0.07123911, 0.22617919])

In [13]:
mu

array([[2.02889543, 0.58387321],
       [1.48504397, 3.96130589],
       [1.26997612, 1.46258317],
       [3.4355634 , 1.58225174],
       [1.47788008, 3.48312234]])

In [14]:
samples[::50]

array([[ 4.17993725,  1.24175583],
       [ 2.68098744,  0.32334823],
       [ 1.41416657,  0.3940763 ],
       [ 3.04086445,  4.25610681],
       [ 1.87104121,  4.03256269],
       [ 5.0214534 ,  1.57025624],
       [ 3.1324006 ,  1.80930315],
       [ 3.48725692,  2.19854219],
       [ 2.67629033, -0.01613154],
       [ 2.5919368 ,  2.00105177],
       [-0.10403355,  0.37719824],
       [ 3.65484623,  1.83349119],
       [ 0.27127926,  2.74596415],
       [ 1.16614525,  1.58661359],
       [ 1.47989679,  0.89424985],
       [ 0.9680544 ,  1.00286455],
       [ 4.67228469,  2.75282497],
       [ 0.3507703 ,  3.45548201],
       [ 2.11184957,  2.31217297],
       [ 2.10118491,  4.49285233]])

In [15]:
adv_sample

array([-1., -1.])

In [ ]:
data_fname = 'data.npz'
np.savez(data_fname, pi=pi, mu=mu, samples=samples, adv_sample=adv_sample)